#!/bin/zsh

script_name=$(basename "$0")

if [ "$#" -ne 3 ]; then
    echo "Usage: $script_name <input_file> <start_time> <end_time>"
    exit 1
fi

input_file="$1"
start_time="$2"
end_time="$3"
output_file="clip_${input_file}"

# Execute ffmpeg command
ffmpeg -ss "$start_time" -to "$end_time" -i "$input_file" -c copy "$output_file"
