#!/usr/bin/env bash

echo "installing fish"
sudo apt update
sudo apt install fish

echo "setting fish to default shell"
chsh -s "$(which fish)"

echo "installing fisher"
curl -sL \
https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish \
| source && fisher install jorgebucaran/fisher

echo "installing pure-fish"
fisher install pure-fish/pure

echo "installing fish-async-prompt"
fisher install acomagu/fish-async-prompt

echo "installing autopair"
fisher install jorgebucaran/autopair.fish
