#!/usr/bin/env bash

if ! command -v ffmpeg &> /dev/null
then
    echo "FFmpeg could not be found."
    exit 1
fi

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <input_file.mp3>"
    exit 1
fi

input_file=$1
output_file="${input_file%.mp3}_clean.mp3"

ffmpeg -i "$input_file" -map_metadata -1 -map 0 -vn -c:a copy "$output_file"


echo "Metadata removed. Output file: $output_file"
